# https://github.com/lycheeverse/lychee
# https://lychee.cli.rs/#/usage/config
exclude = [
  '^https://twitter.com/.*',
  '.*\.md$',
  'https://aquaproj\.github\.io/docs/registry-config#go-package',
]
